library (roxygen)
library (ReadImages)
library (grid)
library (fields)
library (lattice)
library (ggplot2)
library (doMC)
library (akima)
library (foreach)
library (itertools)
source ('utils.r')
source ('misc.r')
source ('bombing.r')
source ('test.r')
source ('figures.r')
source ('figures2.r')
theme_set (theme_bw (base_size = 18))
options (error = recover)
# quartz()
